### ISSUE TITLE
About SPM structure, source code is different from the paper

### ISSUE THREAD

**Issue by weiyu-zeng** [Andrew-Qibin/SPNet#6]
Hi, thank you for your interesting work.
But I'm confused why the strip pooling module(SPM) structure is different from the paper. In the paper, the end of SPM is a sigmoid function and the output of SPM elementwise multiply x, instead of elementwise summation shown in the source code (SPNet/models/customize.py).

**Comment by houqb** [comment]
Thanks for your interests. The SPM is in models/resnet.py. Check it out
there.

Kind regards,
Qibin (Andrew)

**Comment by weiyu-zeng** [comment]
Thanks for your response, my negligence. I will withdraw the issue
