### ISSUE TITLE
About the SPM

### ISSUE THREAD

**Issue by yexiguafuqihao** [Andrew-Qibin/SPNet#7]
It is a very nice job. However, I can't find the schematic illustration strip pooling  module implementation in this codebase, which is depicted in Figure.2 in the paper. Would you please provide me an explanation ?

**Comment by houqb** [comment]
Check it out in the models/resnet.py

Kind regards,
Qibin (Andrew)

**Comment by swjtulinxi** [comment]
actually，The author's model accuracy improvement mainly comes from SPM, not MPM. If we can design complex SPM combination in MPM stage, we should also be able to improve the accuracy

**Comment by swjtulinxi** [comment]
事实上，大佬，你给我们提供的一个新思路就是，对于语义分割来说，目前的后端模块想ppm，aspp，和注意力机制等，其实性能已经足够好了，其实最主要的是，我们后端需要接收来自前端网络的信息，其实前端网络提取的信息往往比后端更重要，新思路就是目前我们可以在前端做工作，因为对后端的改进似乎已经很难了，而且效果也不是很强了
