### ISSUE TITLE
pretrained models download failed

### ISSUE THREAD

**Issue by jinhaijian** [Andrew-Qibin/SPNet#8]
Hi Andrew

When I try to download the  resnet50 and resnet101  pretrained models,  download failed.
the web page shows as below

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7DEA2DF83DD09F16</RequestId>
<HostId>
3xD9N83ctj90a6YVRw5dD0Mrj6Y55HoulIwwQdG5U6i4DYUY/ReBaNBJCyS5BV6r+sg7zcs2WuE=
</HostId>
</Error>

**Comment by houqb** [comment]
Here is the link https://drive.google.com/open?id=1jrm93o5ULjuOHaRQVakVF-e8MC8IAn1X

**Comment by swjtulinxi** [comment]
你好，请问这个版本的resnet34和resnet18权重在哪里下在啊，因为网上只能找到7x7的权重，找不到将7x7卷积换成3个3x3卷积那个版本的权重
